import numpy as np
arr=np.array([10,20,30,40,50])
print('Array elements are:',arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.zeros(5))
print(np.ones(8))
print("Even nubers are:",np.arange(2,20 ,2))
print("Odd numbers are:",np.arange(1,20,2))
n=int(input("Enter the size of array: "))
ele=list(map(int,input("Enter the elements of array: ").split()))
print("Array elements are:",np.array(ele))